name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Base
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: ""
          # Core
          config_timezone: America/Vancouver
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics"
          # Achievements
          plugin_achievements: yes
          # Recent Activity
          plugin_activity: yes
          # Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 5
          # Followup
          plugin_followup: yes
          plugin_followup_sections: user
          # Habits
          plugin_habits: yes
          # Introduction
          plugin_introduction: yes
          # Lines of Code
          plugin_lines: yes
          # Notable Contributions
          plugin_notable: yes
          plugin_notable_from: all
          # Stargazers
          plugin_stargazers: yes
          # Repository Traffic
          plugin_traffic: yes
          # Pagespeed
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://skykings.net
          plugin_pagespeed_detailed: yes
          # Wakatime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          
          
