name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Base
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: ""
          # Core
          config_timezone: America/Vancouver
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics"
          # Languages
          plugin_languages: yes
          # Habits
          plugin_habits: yes
          plugin_habits_charts: yes
          # Followup
          plugin_followup: yes
          plugin_followup_sections: user
          # Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 5
          # Achievements
          #plugin_achievements: yes
          # Recent Activity
          plugin_activity: yes
          plugin_activity_visibility: public
          # Repository Traffic
          plugin_traffic: yes
          # Introduction
          plugin_introduction: yes
          # Wakatime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          # Steam
          #plugin_steam: yes
          #plugin_steam_token: ${{ secrets.STEAM_API_KEY }}
          
          
